[project]
name = "TransReID"
version = "0.1.0"
description = ""
authors = [
    {name = "yanzeradev",email = "yankarlos.solraknay@hotmail.com"}
]
readme = "README.md"
packages = [
    { include = "model" },
    { include = "solver" },
    { include = "datasets" },
    { include = "utils" },
    { include = "loss" },
    { include = "processor" },
]
requires-python = ">=3.10"
dependencies = [
    torch = ">=1.7.1"
    torchvision = ">=0.8.2"
    numpy = "*"
    yacs = "*"
    tqdm = "*"
    Pillow = "*"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
